config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Shoppe::Engine => "/shoppe"

  root :to => 'products#index'

  get 'product/:permalink' => 'products#show', :as => 'product'
  post 'product/:permalink' => 'products#buy', :as => 'buy_product'

  get 'basket' => 'orders#show'
  delete 'basket' => 'orders#destroy'
  
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :post]
  match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via =>[:get, :post]

  get 'categories' => 'categories#index'
  get 'category/:permalink' => 'categories#show', :as => 'category'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  private
  
  # Returns the active order for this session
  def current_order
    @current_order ||= begin
      if has_order?
        @current_order
      else
        order = Shoppe::Order.create(:ip_address => request.ip)
        session[:order_id] = order.id
        order
      end
    end
  end

  # Has an active order?
  def has_order?
    session[:order_id] && @current_order = Shoppe::Order.includes(:order_items => :ordered_item).find_by_id(session[:order_id])
  end
  
  helper_method :current_order, :has_order?
  

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController



	def show
    @category = Shoppe::ProductCategory.find_by_permalink(params[:permalink])

  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def destroy
	  current_order.destroy
	  session[:order_id] = nil
	  redirect_to root_path, :notice => "Basket emptied successfully."
	end
	
	def checkout
  	@order = Shoppe::Order.find(current_order.id)
	end

	def checkout
	  @order = Shoppe::Order.find(current_order.id)
	  if request.patch?
	    if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
	      redirect_to checkout_payment_path
	    end
	  end
	end

	def payment
	  if request.post?
	    redirect_to checkout_confirmation_path
	  end
	end

	def confirmation
	  if request.post?
	    current_order.confirm!
	    session[:order_id] = nil
	    redirect_to root_path, :notice => "Order has been placed successfully!"
	  end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Shoppe::Product.root.ordered.includes(:product_category, :variants)
    @products = @products.group_by(&:product_category)
  end

  def show
    @product = Shoppe::Product.find_by_permalink(params[:permalink])
  end

  def buy
    @product = Shoppe::Product.find_by_permalink!(params[:permalink])
    current_order.order_items.add_item(@product, 1)
    redirect_to product_path(@product.permalink), :notice => "Product has been added successfully!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<h2>Categories</h2>


<p><%= link_to "Back to Products", root_path %></p>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>




<p><%= link_to "Back to Categories", categories_path, :id=> 'categories' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Storefront</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<% if has_order? %>
	<%= render :partial => 'shared/header' %>
<% end %>
<%= yield %>



</body>
</html>

app/views/orders/_items.html.erb
<table width='100%' border='1'>
  <thead>
    <tr>
      <td>Quantity</td>
      <td>Product</td>
      <td>Sub-Total</td>
      <td>Tax</td>
      <td>Total</td>
    </tr>
  </thead>
  <tbody>
    <% order.order_items.each do |item| %>
    <tr>
      <td><%= item.quantity %></td>
      <td><%= item.ordered_item.full_name %></td>
      <td><%= number_to_currency item.sub_total %></td>
      <td><%= number_to_currency item.tax_amount %></td>
      <td><%= number_to_currency item.total %></td>
    </tr>
    <% end %>

    <% if order.delivery_service %>
    <tr>
      <td></td>
      <td><%= order.delivery_service.name %></td>
      <td><%= number_to_currency order.delivery_price %></td>
      <td><%= number_to_currency order.delivery_tax_amount %></td>
      <td><%= number_to_currency order.delivery_price + order.delivery_tax_amount %></td>
    </tr>
    <% end %>

  </tbody>
  <tfoot>
    <tr>
      <td colspan='4'>Sub-Total</td>
      <td><%= number_to_currency order.total_before_tax %></td>
    </tr>
    <tr>
      <td colspan='4'>Tax</td>
      <td><%= number_to_currency order.tax %></td>
    </tr>
    <tr>
      <td colspan='4'>Total</td>
      <td><%= number_to_currency order.total %></td>
    </tr>
  </tfoot>
</table>

app/views/orders/checkout.html.erb
<h2>Checkout</h2>
<%= render 'items', :order => @order %>

<%= form_for @order, :url => checkout_path do |f| %>
  <dl>
    <dt><%= f.label :first_name, 'First Name' %></dt>
    <dd><%= f.text_field :first_name %></dd>
    <dt><%= f.label :first_name, 'Last Name' %></dt>
    <dd><%= f.text_field :last_name %></dd>

    <dt><%= f.label :billing_address1, 'Address Line 1' %></dt>
    <dd><%= f.text_field :billing_address1 %></dd>
    <dt><%= f.label :billing_address1, 'Address Line 2' %></dt>
    <dd><%= f.text_field :billing_address2 %></dd>
    <dt><%= f.label :billing_address1, 'City' %></dt>
    <dd><%= f.text_field :billing_address3 %></dd>
    <dt><%= f.label :billing_address1, 'State' %></dt>    
    <dd><%= f.text_field :billing_address4 %></dd>
    <dt><%= f.label :billing_address1, 'Zip Code' %></dt>
    <dd><%= f.text_field :billing_postcode %></dd>
    
    <dd><%= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :include_blank => true %></dd>

    <dt><%= f.label :email_address, 'Email' %></dt>
    <dd><%= f.text_field :email_address %></dd>

    <dt><%= f.label :phone_number %></dt>
    <dd><%= f.text_field :phone_number %></dd>

    <dd><%= f.submit 'Continue' %></dd>
  </dl>
<% end %>

app/views/orders/confirmation.html.erb
<h2>Place your order</h2>
<%= render 'items', :order => current_order %>
<%= button_to "Place order" %>

app/views/orders/orders.html.erb
<h2>Your basket</h2>
<%= render 'items', :order => current_order %>

app/views/orders/payment.html.erb
<h2>Make your payment</h2>
<%= form_tag do %>
  <dl>
    <dt><%= label_tag 'card_number' %></dt>
    <dd><%= text_field_tag 'card_number' %></dd>
    <dt><%= label_tag 'expiry' %></dt>
    <dd><%= text_field_tag 'expiry' %></dd>
    <dt><%= label_tag 'security_code' %></dt>
    <dd><%= text_field_tag 'security_code' %></dd>
    <dd><%= submit_tag "Continue" %></dd>
  </dl>
<% end %>

app/views/orders/show.html.erb
<h2>Your basket</h2>
<%= render 'items', :order => current_order %>
<p><%= link_to "Back to list", root_path %></p>
<p><%= link_to 'Empty basket', basket_path, :method => :delete %></p>

app/views/products/index.html.erb
<section class="container">
  <h2>Products</h2>
  <% @products.each do |category, products| %>  
    <div class="row col-sm-6 col-xs-12" >
      <div class="col-sm-12 col-xs-12">
        <h3><%= link_to category.name, category_path(category.permalink) %></h3>
        <ul>
          <% products.each do |product| %>
          <li>
            <h4><%= link_to product.name, product_path(product.permalink) %></h4>
            <p><%= truncate(product.short_description, length: 135) %></p>
            <p><b>Price:</b> <%= number_to_currency product.price %></p>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</section>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>

<%= render :partial => 'shared/breadcrumbs' %>

<% if @product.default_image %>
  <%= image_tag @product.default_image.path, :width => '200px', :style => "float:right" %>
<% end %>

<p><%= @product.short_description %></p>
<p>
  <b><%= number_to_currency @product.price %></b>
  <%= link_to "Add to basket", buy_product_path(@product.permalink), :method => :post %>
</p>

<hr>
<%= simple_format @product.description %>
<hr>

<p><%= link_to "Back to list", root_path %></p>
<p><%= link_to 'Empty basket', basket_path, :method => :delete %></p>

app/views/shared/_breadcrumbs.html.erb
<ul id="breadcrumb_trail">
	<li><%= link_to "Home", :controller => "products", :action => "index" %></li>
	<li>&gt;</li>
	<li><%= @product.name %></li>
</ul>

app/views/shared/_header.html.erb
<section id="cart">
	<p>
	  You have <%= pluralize current_order.total_items, 'item'%> in your basket which cost
	  <%= number_to_currency current_order.total_before_tax %>.
	</p>
	<%= link_to "View basket", basket_path %>
	<%= link_to "Checkout", checkout_path %>
</section>